# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend main cicd

on:
  push:
    branches: [ "master" ]
    
defaults:
  run:
    shell: bash
    working-directory: ./
    
jobs:
  build:
    # runner for the job
    runs-on: ubuntu-latest 
    steps:
    # get the code
    - name: checkout
      uses: actions/checkout@v4.1.7
    # install nodejs
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.3
      with:
        # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
        node-version: 20.x
    # install du projet  
    - name: npm install
      run: npm install
    - name: cache setup
      uses: actions/cache@v4.0.2
      with:
        path: node_modules
        key: npmi-${{ hashFiles('package-lock.json') }} # npmi-c1458sjki...

  tu:
    # runner for the job
    runs-on: ubuntu-latest 
    needs: build # start this after the build job
    steps:
      # install nodejs
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 20.x
      # get the code
      - name: checkout
        uses: actions/checkout@v4.1.7
      - name: cache setup
        uses: actions/cache@v4.0.2
        with:
          path: node_modules
          key: npmi-${{ hashFiles('package-lock.json') }} # npmi-c1458sjki...
      - name: TU 
        run: npm run test
    
